# https://shopping-manager.kakaosecure.net/api/product/gift/products/search?itemType=SHIPPING&productName=&sellerManagementCodes=&productIds=&brand=&giftBrand=&modelName=&manufacturer=&directBuying=&statuses=ON_SALE&categoryId=101111106&periodType=REGISTRATION_DATE&from=20140101000000&to=20240801235959&b2b=&displayable=&shoppingHowDisplayable=&stockQuantity=&sellerDiscount=&adminDiscount=&maxSaleQuantityEnabled=&isolatedAreaDeliverable=&booked=&maxPurchaseQuantityOfBuyer=&giftType=&suggestionNameExists=&eventNameExists=&size=100&approverName=&sellerId=&sellerName=&agencySellerId=&approveStatus=APPROVED&ctm=&slidingDiscount=&salePromotion=&productFee=&managedPrice=&priceRelatedPropertiesModify=&openApiRegistration=&bundleGroupAvailable=&deliveryMethodType=&isolatedAreaPickupAvailable=&pickupAvailableStoreType=&sameDayPickup=&pickupStoreChangeable=&optionChangeable=&giftPurchaseType=&displaySpace=&secretStore=&detailBuyingType=&giftPackaging=&customOrder=&advertisementReviewType=&advertisementReviewRequired=&advertisementReviewUploaded=&fixedDateGift=&approverSearchType=BRAND&cert=&valex=&showrooming=&monitoringStatuses=&monitoringChangedType=&prohibitionReasonType=&displayComparisonDiscountRate=&discountDisplayPolicy=&giftBrandIds=&fandom=&page=0&sortProperty=lastModifiedAt&sortType=desc&_t=1722495772708



curl -X 'GET' \
  'https://beta-product-aapi.kakao.com/GIFT/products/search?itemType=SHIPPING&productName=&sellerManagementCodes=&productIds=&brand=&giftBrand=&modelName=&manufacturer=&directBuying=&statuses=ON_SALE&categoryId=101111106&periodType=REGISTRATION_DATE&from=20140101000000&to=20240801235959&b2b=&displayable=&shoppingHowDisplayable=&stockQuantity=&sellerDiscount=&adminDiscount=&maxSaleQuantityEnabled=&isolatedAreaDeliverable=&booked=&maxPurchaseQuantityOfBuyer=&giftType=&suggestionNameExists=&eventNameExists=&size=100&approverName=&sellerId=&sellerName=&agencySellerId=&approveStatus=APPROVED&ctm=&slidingDiscount=&salePromotion=&productFee=&managedPrice=&priceRelatedPropertiesModify=&openApiRegistration=&bundleGroupAvailable=&deliveryMethodType=&isolatedAreaPickupAvailable=&pickupAvailableStoreType=&sameDayPickup=&pickupStoreChangeable=&optionChangeable=&giftPurchaseType=&displaySpace=&secretStore=&detailBuyingType=&giftPackaging=&customOrder=&advertisementReviewType=&advertisementReviewRequired=&advertisementReviewUploaded=&fixedDateGift=&approverSearchType=BRAND&cert=&valex=&showrooming=&monitoringStatuses=&monitoringChangedType=&prohibitionReasonType=&displayComparisonDiscountRate=&discountDisplayPolicy=&giftBrandIds=&fandom=&page=0&sortProperty=lastModifiedAt&sortType=desc&_t=1722495772708' \
  -H 'accept: */*' \
  -H 'x-user-type: MANAGER' \
  -H 'Authorization: yon.du' \
  | jq . > request-search.json